name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: ppip install mkdocs-material mkdocs-snippets  mkdocs-tooltips https://github.com/bmcorser/fontawesome-markdown/archive/master.zip
      - run: mkdocs gh-deploy --force